services:
  - type: web
    name: axion-digitaverse-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind=0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0